// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE49XchrZ9zax-7FmJNXeh50_jigL7mYk',
    appId: '1:447122321425:web:0357af58d3283bf5ea81b0',
    messagingSenderId: '447122321425',
    projectId: 'flash-2-mart',
    authDomain: 'flash-2-mart.firebaseapp.com',
    storageBucket: 'flash-2-mart.firebasestorage.app',
    measurementId: 'G-6PBRCP8ELZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJvMKd-N-DBbGIGQxyyy7gzBoroWuKAI',
    appId: '1:447122321425:android:b071e62fbb985f8eea81b0',
    messagingSenderId: '447122321425',
    projectId: 'flash-2-mart',
    storageBucket: 'flash-2-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmDun_OnF-lza3eCmifjKHraW2dbiesXk',
    appId: '1:447122321425:ios:417a1a2cc503a154ea81b0',
    messagingSenderId: '447122321425',
    projectId: 'flash-2-mart',
    storageBucket: 'flash-2-mart.firebasestorage.app',
    iosBundleId: 'com.example.flash2mart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmDun_OnF-lza3eCmifjKHraW2dbiesXk',
    appId: '1:447122321425:ios:417a1a2cc503a154ea81b0',
    messagingSenderId: '447122321425',
    projectId: 'flash-2-mart',
    storageBucket: 'flash-2-mart.firebasestorage.app',
    iosBundleId: 'com.example.flash2mart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE49XchrZ9zax-7FmJNXeh50_jigL7mYk',
    appId: '1:447122321425:web:82e24007c3152766ea81b0',
    messagingSenderId: '447122321425',
    projectId: 'flash-2-mart',
    authDomain: 'flash-2-mart.firebaseapp.com',
    storageBucket: 'flash-2-mart.firebasestorage.app',
    measurementId: 'G-E8PKECRSW7',
  );
}
